### ISSUE TITLE
How to use this for our custom images?

### ISSUE THREAD

**Issue by kashishnaqvi101** [SizheAn/PanoHead#16]
Hello, I would like to know how can I use my own images(downloaded from the internet or clicked from camera) and generate a 360 degree 3d model? Do we have to generate latents using StyleGAN3 and then feed this to the model?

**Comment by SizheAn** [comment]
We update the scripts and example data for obtaining camera poses and cropping the images for PTI. See https://github.com/SizheAn/PanoHead/blob/main/3DDFA_V2_cropping/cropping_guide.md

**Comment by electrodrago** [comment]
when using the code of 3DDFA, I ran into a problem of some libraries cannot import, can you also provide the codes for it

**Comment by kashishnaqvi101** [comment]
> We update the scripts and example data for obtaining camera poses and cropping the images for PTI. See https://github.com/SizheAn/PanoHead/blob/main/3DDFA_V2_cropping/cropping_guide.md

thanks for the guidance I also wanted to know how can we generate shapes along with the .mp4 files for our custom images ? I was just able to generate the video
