### ISSUE TITLE
How to export different angle images with my own input?

### ISSUE THREAD

**Issue by zobnechopin** [SizheAn/PanoHead#23]
I can generate full head reconstruction video from a single RGB file by use ./gen_pti_script.sh, but how to export different angle images with my own input by use gen_samples.py?

**Comment by SizheAn** [comment]
Check https://github.com/SizheAn/PanoHead/blob/17ad915941c7e2703d5aa3eb5ff12eac47c90e53/gen_samples.py#L182-L183 for how to specify the angles

**Comment by zobnechopin** [comment]
> Check
> 
> https://github.com/SizheAn/PanoHead/blob/17ad915941c7e2703d5aa3eb5ff12eac47c90e53/gen_samples.py#L182-L183
> 
> for how to specify the angles

But this method can't use my own input image? It's said "Generate images using pretrained network pickle".

**Comment by SizheAn** [comment]
> > Check
> > https://github.com/SizheAn/PanoHead/blob/17ad915941c7e2703d5aa3eb5ff12eac47c90e53/gen_samples.py#L182-L183
> > 
> > for how to specify the angles
> 
> But this method can't use my own input image? It's said "Generate images using pretrained network pickle".

You can follow this fork: https://github.com/camenduru/PanoHead-colab to reconstruct a head using your own image and change the code properly to specify angles.

**Comment by Hyunju37** [comment]
Hello. Did you get the result from gen_sample.py with your own image? If you did so, can you tell me how?
