### ISSUE TITLE
tri-grid projection

### ISSUE THREAD

**Issue by oneThousand1000** [SizheAn/PanoHead#28]
Hello, thank you for sharing your interesting work!

The authors of EG3D mentioned that their triplane projection is actually a bi-plane projection (XY, XZ, ZX) (see https://github.com/NVlabs/eg3d/issues/67). After examining your code, it seems that this issue is still present. I'm wondering if you have considered the potential problems that may arise from this projection method in the proposed tri-grid?

I look forward to your kind reply!

**Comment by SizheAn** [comment]
We already considered and fixed it:

https://github.com/SizheAn/PanoHead/blob/main/training/volumetric_rendering/renderer.py#L15-L29

The tri-plane projection here is XY, XZ, **YZ**, whereas in your link the fix Eric provided is XY, XZ, **ZY**. They are essentially the same.

**Comment by oneThousand1000** [comment]
Thanks!
