### ISSUE TITLE
Details about Pre-trained Models?

### ISSUE THREAD

**Issue by kyustorm7** [SizheAn/PanoHead#3]
Hi, thanks for the great work and for sharing this helpful repository. 
However, I do have some questions about the provided pre-trained models.
I see you provided 3 pkl files, and I can infer that the easy-khair-180-gpc0.8-trans10-025000.pkl is the desired one to use. 

Could you also provide me some details about how the other two models differ from that one? 
Thanks a lot.

**Comment by SizheAn** [comment]
Basically only the easy-khair-180-gpc0.8-trans10-025000.pk is a good checkpoint that we release for demo. baseline is basically eg3d, but trained with our data. And the ablation one is when tri-grid's depth = 1.

**Comment by kyustorm7** [comment]
Thanks a lot!
