### ISSUE TITLE
Dataset.json generation

### ISSUE THREAD

**Issue by carlosedubarreto** [SizheAn/PanoHead#7]
Im trying to use it with other images, but I'm having a hard time on how to generate the dataset.json file.

Can you point a direction on how to make it?

Thanks
This is a great solution that youve made.

**Comment by SizheAn** [comment]
Working on it! I think in here https://github.com/SizheAn/PanoHead/issues/13#issuecomment-1607769030 people are also closed to reproduce it.

**Comment by SizheAn** [comment]
> Thanks a lot @SizheAn this data was drinving me crazy this last weekend 😀

We update the scripts and example data for obtaining camera poses and cropping the images for PTI. See https://github.com/SizheAn/PanoHead/blob/main/3DDFA_V2_cropping/cropping_guide.md

**Comment by carlosedubarreto** [comment]
Seems like the shape predictor needs to be downloaded from here

https://github.com/italojs/facial-landmarks-recognition/blob/master/shape_predictor_68_face_landmarks.dat

I'm testin it right now. Thanks a lot @SizheAn

**Comment by carlosedubarreto** [comment]
Got a great result at the front part.
Just an odd result at the back of the face. But great results overall
thanks a lot for that. I'll make a lot more tests 🎉

https://github.com/SizheAn/PanoHead/assets/4061130/5fc1f00d-d0e1-48cf-bab1-2c3cbe5d9ecb

**Comment by kashishnaqvi101** [comment]
> Got a great result at the front part. Just an odd result at the back of the face. But great results overall thanks a lot for that. I'll make a lot more tests 🎉
> 
>  Post1.mp4

Hey, I got an error called no module Faceboxes, did you get any such error?

**Comment by carlosedubarreto** [comment]
@kashishnaqvi101 yep, me too.
You have to get most of the things from the 3DDFA repository. you will also have to compile a couple of things.

Nothing impossible, it will just give you a few more work, but totally worth it.

**Comment by kashishnaqvi101** [comment]
> @kashishnaqvi101 yep, me too. You have to get most of the things from the 3DDFA repository. you will also have to compile a couple of things.
> 
> Nothing impossible, it will just give you a few more work, but totally worth it.

Yeah, it finally ran! and the results are good, i just need them in some mesh format so that an animator can actually use it

**Comment by carlosedubarreto** [comment]
@kashishnaqvi101 I suggest you to take a look on Hackman repository, he made some changes that can enable the mesh output

https://github.com/hack-mans/PanoHead

**Comment by kashishnaqvi101** [comment]
> @kashishnaqvi101 I suggest you to take a look on Hackman repository, he made some changes that can enable the mesh output
> 
> https://github.com/hack-mans/PanoHead

Thanks for the help, I will out hack-man's version!

**Comment by kashishnaqvi101** [comment]
Okay, thank you. I got the output in no colour, I hope they someone
introduces colours also.
