### ISSUE TITLE
ResolvePackageNotFound 

### ISSUE THREAD

**Issue by amaruzeas** [SizheAn/PanoHead#9]
ResolvePackageNotFound:
 - cudatoolkit=11.1

Not sure how to solve this issue

**Comment by SizheAn** [comment]
I'm not sure either. Are you in conda environment? And what hardware spec are you using?

**Comment by btaens** [comment]
Having the same issue. I'm on Windows 11, Anaconda3 (Python 3.11.4 64-bit).

**Comment by btaens** [comment]
Solved it, had to add "conda-forge" to the channels in environment.yml.
